import uuid

import datetime
from django.contrib.auth.models import AbstractUser

from django.db import models

class msch(models.Model):
	ms_id = models.CharField(max_length=10, primary_key=True, verbose_name='멘토스쿨ID' )
	status = models.CharField(max_length=2, null=True, blank=True, verbose_name='상태' )
	ms_name = models.CharField(max_length=100, null=True, blank=True, verbose_name='멘토스쿨 명' )
	ms_sname = models.CharField(max_length=20, null=True, blank=True, verbose_name='멘토스쿨 단명' )
	ms_intro = models.CharField(max_length=1000, null=True, blank=True, verbose_name='멘토스쿨 소개' )
	mng_area = models.CharField(max_length=2, null=True, blank=True, verbose_name='멘토스쿨 관리 영역' )
	mgr_id = models.CharField(max_length=10, null=True, blank=True, verbose_name='멘토스쿨 관리자 ID' )
	mgr_nm = models.CharField(max_length=20, null=True, blank=True, verbose_name='멘토스쿨 관리자 명' )
	mng_org = models.CharField(max_length=10, null=True, blank=True, verbose_name='관리기관' )
	sup_org = models.CharField(max_length=10, null=True, blank=True, verbose_name='주관기관' )
	yr = models.CharField(max_length=4, null=True, blank=True, verbose_name='연도' )
	yr_seq = models.PositiveIntegerField(null=True, blank=True, verbose_name='차수' )
	apl_ntc_fr_dt = models.DateTimeField(null=True, blank=True, verbose_name='공지시작일' )
	apl_ntc_to_dt = models.DateTimeField(null=True, blank=True, verbose_name='공지종료일' )
	apl_term = models.CharField(max_length=2, null=True, blank=True, verbose_name='모집시기(MS0022)' )
	apl_fr_dt = models.DateTimeField(null=True, blank=True, verbose_name='모집기간-시작' )
	apl_to_dt = models.DateTimeField(null=True, blank=True, verbose_name='모집기간-종료' )
	trn_term = models.CharField(max_length=2, null=True, blank=True, verbose_name='교육시기(MS0022)' )
	trn_fr_dt = models.DateTimeField(null=True, blank=True, verbose_name='교육기간-시작' )
	trn_to_dt = models.DateTimeField(null=True, blank=True, verbose_name='교육기간-종료' )
	tot_apl = models.PositiveIntegerField(default=0, verbose_name='모집인원(정원)-합격' )
	cnt_apl = models.PositiveIntegerField(default=0, verbose_name='지원인원' )
	cnt_doc_suc = models.PositiveIntegerField(default=0, verbose_name='서류전형 합격인원' )
	cnt_doc_res = models.PositiveIntegerField(default=0, verbose_name='서류전형 예비인원(실제 없음)' )
	cnt_intv_pl = models.PositiveIntegerField(default=0, verbose_name='면접전형 참여 계획 인원' )
	cnt_intv_ac = models.PositiveIntegerField(default=0, verbose_name='면접전형 참여 인원' )
	intv_dt = models.CharField(max_length=8, null=True, blank=True, verbose_name='면접일' )
	cnt_intv_suc = models.PositiveIntegerField(default=0, verbose_name='면접전형 합격인원' )
	cnt_iintv_res = models.PositiveIntegerField(default=0, verbose_name='면접전형 예비합격인원' )
	cnt_trn = models.PositiveIntegerField(default=0, verbose_name='교육인원' )
	cnt_mtr = models.PositiveIntegerField(default=0, verbose_name='최종합격 멘토인원' )
	doc_dt = models.DateTimeField(null=True, blank=True, verbose_name='서류전형일' )
	doc_mgr = models.CharField(max_length=10, null=True, blank=True, verbose_name='서류전형 수행자' )
	intv_dt = models.DateTimeField(null=True, blank=True, verbose_name='면접전형-입력-일' )
	intv_mgr = models.CharField(max_length=10, null=True, blank=True, verbose_name='면접전형-입력-자' )
	fin_dt = models.DateTimeField(null=True, blank=True, verbose_name='최종합격-입력-일' )
	fin_mgr = models.CharField(max_length=10, null=True, blank=True, verbose_name='최종합격-입력-자' )
	ins_id = models.CharField(max_length=10, null=True, blank=True, verbose_name='입력자ID' )
	ins_ip = models.CharField(max_length=20, null=True, blank=True, verbose_name='입력자IP' )
	ins_dt = models.DateTimeField(null=True, blank=True, verbose_name='입력일시' )
	ins_pgm = models.CharField(max_length=20, null=True, blank=True, verbose_name='입력프로그램ID' )
	upd_id = models.CharField(max_length=10, null=True, blank=True, verbose_name='수정자ID' )
	upd_ip = models.CharField(max_length=20, null=True, blank=True, verbose_name='수정자IP' )
	upd_dt = models.DateTimeField(null=True, blank=True, verbose_name='수정일시' )
	upd_pgm = models.CharField(max_length=20, null=True, blank=True, verbose_name='수정프로그램ID' )

class Meta:
	verbose_name = '개설멘토스쿨'
	verbose_name_plural =  verbose_name



class ms_apl(models.Model):
	ms_id = models.CharField(max_length=10, null=False, verbose_name='멘토스쿨ID' )
	apl_no = models.PositiveIntegerField(null=False, verbose_name='지원 NO' )
	apl_id = models.CharField(max_length=10, null=False, verbose_name='지원자ID(학번)' )
	apl_nm = models.CharField(max_length=20, null=False, verbose_name='지원자 명' )
	apl_nm_e = models.CharField(max_length=20, null=True, blank=False, verbose_name='멘토 영문명' )
	unv_cd = models.CharField(max_length=10, null=False, verbose_name='지원자 대학교 코드' )
	unv_nm = models.CharField(max_length=10, null=False, verbose_name='지원자 대학교 명' )
	cllg_cd = models.CharField(max_length=10, null=False, verbose_name='지원자 대학 코드' )
	cllg_nm = models.CharField(max_length=10, null=False, verbose_name='지원자 대학 명' )
	dept_cd = models.CharField(max_length=10, null=False, verbose_name='지원자 학부/학과 코드' )
	dept_nm = models.CharField(max_length=10, null=False, verbose_name='지원자 학부/학과 명' )
	brth_dt = models.CharField(max_length=8, null=False, verbose_name='생년월일' )
	gen = models.CharField(max_length=1, null=False, verbose_name='성별' )
	yr = models.CharField(max_length=4, null=False, verbose_name='학년도' )
	term_div = models.CharField(max_length=2, null=False, verbose_name='학기' )
	sch_yr = models.CharField(max_length=1, null=False, verbose_name='학년' )
	mob_no = models.CharField(max_length=12, null=False, verbose_name='휴대전화' )
	tel_no = models.CharField(max_length=12, null=True, blank=True, verbose_name='집전화' )
	tel_no_g = models.CharField(max_length=12, null=True, blank=True, verbose_name='보호자 연락처' )
	h_addr = models.CharField(max_length=200, null=False, verbose_name='집주소' )
	post_no = models.CharField(max_length=6, null=True, blank=True, verbose_name='우편번호' )
	email_addr = models.CharField(max_length=50, null=True, blank=True, verbose_name='이메일 주소' )
	apl_dt = models.DateTimeField(null=True, blank=True, verbose_name='접수일(지원서 저장)' )
	status = models.CharField(max_length=1, null=True, blank=True, verbose_name='상태(지원,취소,…)' )
	doc_cncl_dt = models.DateTimeField(null=True, blank=True, verbose_name='지원취소일' )
	doc_cncl_rsn = models.CharField(max_length=2, null=True, blank=True, verbose_name='서류전형취소사유' )
	tot_doc = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='서류전형  총 점수' )
	score1 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='원점수1(성적,봉사,외국어,지원서)' )
	score2 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='원점수2' )
	score3 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='원점수3' )
	score4 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='원점수4' )
	score5 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='원점수5' )
	score6 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='원점수6' )
	cscore1 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='변환점수1' )
	cscore2 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='변환점수2' )
	cscore3 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='변환점수3' )
	cscore4 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='변환점수4' )
	cscore5 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='변환점수5' )
	cscore6 = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='변환점수6' )
	doc_rank = models.PositiveIntegerField(null=True, blank=True, verbose_name='서류심사등수' )
	doc_rslt = models.CharField(max_length=1, null=True, blank=True, verbose_name='서류심사결과' )
	intv_team = models.PositiveIntegerField(null=True, blank=True, verbose_name='면접팀' )
	intv_dt = models.DateTimeField(null=True, blank=True, verbose_name='면접일' )
	intv_part_pl = models.CharField(max_length=1, null=True, blank=True, verbose_name='면접참여계획' )
	intv_np_rsn_pl = models.CharField(max_length=2, null=True, blank=True, verbose_name='면접불참사유' )
	intv_part_pl_dt = models.DateTimeField(null=True, blank=True, verbose_name='면접참여계획 입력일' )
	intv_part_ac = models.CharField(max_length=1, null=True, blank=True, verbose_name='면접참여여부' )
	intv_np_rsn_ac = models.CharField(max_length=2, null=True, blank=True, verbose_name='면접불참사유' )
	intv_part_ac_dt = models.DateTimeField(null=True, blank=True, verbose_name='면접참여 입력일' )
	intv_tot = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='면접점수' )
	intv_rslt = models.CharField(max_length=1, null=True, blank=True, verbose_name='면접심사결과' )
	ms_trn_yn = models.CharField(max_length=1, null=True, blank=True, verbose_name='멘토스쿨 이수여부' )
	fnl_rslt = models.CharField(max_length=1, null=True, blank=True, verbose_name='최종합격 여부' )
	mntr_id = models.CharField(max_length=10, null=True, blank=True, verbose_name='멘토ID' )
	mntr_dt = models.DateField(null=True, blank=True, verbose_name='멘토 자격 부여일' )
	sms_send_no = models.CharField(max_length=20, null=True, blank=True, verbose_name='문자발송번호' )
	ins_id = models.CharField(max_length=10, null=True, blank=True, verbose_name='입력자ID' )
	ins_ip = models.CharField(max_length=20, null=True, blank=True, verbose_name='입력자IP' )
	ins_dt = models.DateTimeField(null=True, blank=True, verbose_name='입력일시' )
	ins_pgm = models.CharField(max_length=20, null=True, blank=True, verbose_name='입력프로그램ID' )
	upd_id = models.CharField(max_length=10, null=True, blank=True, verbose_name='수정자ID' )
	upd_ip = models.CharField(max_length=20, null=True, blank=True, verbose_name='수정자IP' )
	upd_dt = models.DateTimeField(null=True, blank=True, verbose_name='수정일시' )
	upd_pgm = models.CharField(max_length=20, null=True, blank=True, verbose_name='수정프로그램ID' )

	class Meta:
		verbose_name = '멘토스쿨 지원자'
		verbose_name_plural =  verbose_name
		unique_together=("ms_id", "apl_no")
		index_together = ["apl_id"]
		index_together = ["apl_nm"]

# Create your models here.
