# Generated by Django 2.1.5 on 2019-02-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('mntr_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='멘토ID')),
                ('mntr_nm', models.CharField(max_length=20, verbose_name='멘토 명')),
                ('mntr_nm_e', models.CharField(max_length=20, verbose_name='멘토 영문명')),
                ('ms_id', models.CharField(max_length=10, verbose_name='멘토스쿨ID')),
                ('apl_no', models.PositiveIntegerField(max_length=1, verbose_name='지원 NO')),
                ('apl_id', models.CharField(max_length=10, verbose_name='지원자ID(학번)')),
                ('mntr_dt', models.DateField(verbose_name='멘토 자격 부여일')),
                ('unv_cd', models.CharField(max_length=10, verbose_name='멘토 대학교 코드')),
                ('unv_nm', models.CharField(max_length=30, verbose_name='멘토 대학교 명')),
                ('cllg_cd', models.CharField(max_length=10, verbose_name='멘토 대학 코드')),
                ('cllg_nm', models.CharField(max_length=30, verbose_name='멘토 대학 명')),
                ('dept_cd', models.CharField(max_length=10, verbose_name='멘토 학부/학과 코드')),
                ('dept_nm', models.CharField(max_length=30, verbose_name='멘토 학부/학과 명')),
                ('brth_dt', models.CharField(max_length=8, verbose_name='생년월일')),
                ('gen', models.CharField(max_length=1, verbose_name='성별')),
                ('yr', models.CharField(max_length=4, verbose_name='학년도')),
                ('term_div', models.CharField(max_length=2, verbose_name='학기')),
                ('sch_yr', models.CharField(max_length=1, verbose_name='학년')),
                ('exp_dt', models.DateField(blank=True, null=True, verbose_name='멘토 자격 박탈일')),
                ('exp_rsn', models.CharField(blank=True, max_length=10, null=True, verbose_name='자격박탈 사유')),
                ('mob_no', models.CharField(blank=True, max_length=12, null=True, verbose_name='휴대전화')),
                ('tel_no', models.CharField(blank=True, max_length=12, null=True, verbose_name='집전화')),
                ('tel_no_g', models.CharField(blank=True, max_length=12, null=True, verbose_name='보호자 연락처')),
                ('h_addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='집주소')),
                ('post_no', models.CharField(blank=True, max_length=6, null=True, verbose_name='우편번호')),
                ('email_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='이메일 주소')),
                ('bank_acct', models.CharField(blank=True, max_length=20, null=True, verbose_name='은행 계좌 번호')),
                ('bank_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='은행 명')),
                ('bank_dpsr', models.CharField(blank=True, max_length=20, null=True, verbose_name='예금주')),
                ('cnt_mp_a', models.PositiveIntegerField(default=0, verbose_name='멘토링 지원 경력')),
                ('cnt_mp_p', models.PositiveIntegerField(default=0, verbose_name='멘토링 수행 경력')),
                ('cnt_mp_c', models.PositiveIntegerField(default=0, verbose_name='멘토링 완료 경력')),
                ('cnt_mp_g', models.PositiveIntegerField(default=0, verbose_name='멘토링 중도포기 경력')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
            options={
                'verbose_name': '멘토',
                'verbose_name_plural': '멘토',
            },
        ),
    ]
