# Generated by Django 2.1.5 on 2019-02-01 06:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service10', '0002_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='mentor',
        ),
    ]
