# Generated by Django 2.1.5 on 2019-02-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service10', '0004_vm_nanum_stdt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='com_cdd',
        ),
    ]
