# Generated by Django 2.1.5 on 2019-02-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service10', '0005_delete_com_cdd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='com_cdh',
        ),
    ]
