# Generated by Django 2.1.5 on 2019-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msch',
            name='img_src',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='이미지경로'),
        ),
    ]
