# Generated by Django 2.1.5 on 2019-02-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0008_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='cm_cnv_scr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_item', models.CharField(max_length=2, verbose_name='항목')),
                ('eval_seq', models.PositiveIntegerField(verbose_name='순서')),
                ('min_scr', models.PositiveIntegerField(verbose_name='최소 점수')),
                ('max_scr', models.PositiveIntegerField(verbose_name='최대 점수')),
                ('eval_unit', models.CharField(max_length=10, verbose_name='단위')),
                ('fin_scr', models.PositiveIntegerField(verbose_name='점수')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
            options={
                'verbose_name': '점수변환표',
                'verbose_name_plural': '점수변환표',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cm_cnv_scr',
            unique_together={('eval_item', 'eval_seq')},
        ),
    ]
