# Generated by Django 2.1.5 on 2019-02-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0009_auto_20190201_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ms_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.CharField(max_length=10, verbose_name='멘토스쿨ID')),
                ('test_div', models.CharField(max_length=10, verbose_name='전형구분(서류/면접)')),
                ('apl_no', models.CharField(max_length=10, verbose_name='지원 NO')),
                ('ques_no', models.PositiveIntegerField(verbose_name='질문 번호')),
                ('apl_id', models.CharField(max_length=10, verbose_name='지원자ID(학번)')),
                ('apl_nm', models.CharField(max_length=20, verbose_name='지원자 명')),
                ('sort_seq', models.PositiveIntegerField(verbose_name='정렬')),
                ('ans_t1', models.PositiveIntegerField(blank=True, null=True, verbose_name='선다형 답')),
                ('ans_t2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='수필형 답')),
                ('ans_t3', models.CharField(blank=True, max_length=2, null=True, verbose_name='선택 답')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='점수')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
            options={
                'verbose_name': '지원서 답변',
                'verbose_name_plural': '지원서 답변',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ms_ans',
            unique_together={('ms_id', 'test_div', 'apl_no', 'ques_no')},
        ),
    ]
