# Generated by Django 2.1.5 on 2019-02-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0010_auto_20190201_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ms_mrk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.CharField(max_length=10, verbose_name='멘토스쿨ID')),
                ('test_div', models.CharField(max_length=10, verbose_name='전형구분(서류/면접)')),
                ('apl_no', models.CharField(max_length=10, verbose_name='지원 NO')),
                ('mrk_seq', models.PositiveIntegerField(verbose_name='채점 항목 SEQ(NO)')),
                ('mrk_no', models.PositiveIntegerField(verbose_name='채점자 NO')),
                ('mrk_id', models.CharField(max_length=10, verbose_name='채점자 ID')),
                ('mak_nm', models.CharField(max_length=20, verbose_name='채점자 명')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='점수')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
            options={
                'verbose_name': '지원서 채점',
                'verbose_name_plural': '지원서 채점',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ms_mrk',
            unique_together={('ms_id', 'test_div', 'apl_no', 'mrk_seq', 'mrk_no')},
        ),
    ]
