# Generated by Django 2.1.5 on 2019-02-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0014_mp_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='guardian',
            fields=[
                ('grdn_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='보호자ID')),
                ('grdn_nm', models.CharField(max_length=20, verbose_name='보호자명')),
                ('grdn_nm_e', models.CharField(max_length=20, verbose_name='보호자 영문명')),
                ('rel_tp', models.CharField(blank=True, max_length=2, null=True, verbose_name='관계')),
                ('brth_dt', models.CharField(max_length=8, verbose_name='생년월일(+ 멘티명 → 동일인 찾기)')),
                ('mob_no', models.CharField(blank=True, max_length=12, null=True, verbose_name='휴대전화')),
                ('tel_no', models.CharField(blank=True, max_length=12, null=True, verbose_name='집전화')),
                ('moth_nat_cd', models.CharField(max_length=10, verbose_name='출신국가코드')),
                ('moth_nat_nm', models.CharField(max_length=20, verbose_name='출신국가명')),
                ('tch_id', models.CharField(max_length=10, verbose_name='지도교사 ID')),
                ('h_addr', models.CharField(max_length=200, verbose_name='집주소')),
                ('h_post_no', models.CharField(blank=True, max_length=6, null=True, verbose_name='우편번호')),
                ('email_addr', models.CharField(max_length=50, verbose_name='이메일 주소')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
