# Generated by Django 2.1.5 on 2019-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0017_auto_20190201_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='apl_no',
            field=models.PositiveIntegerField(verbose_name='지원 NO'),
        ),
    ]
