# Generated by Django 2.1.5 on 2019-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0019_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_apl',
            name='apl_no',
            field=models.IntegerField(verbose_name='지원 NO'),
        ),
    ]
