# Generated by Django 2.1.5 on 2019-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0020_auto_20190207_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_apl',
            name='mob_no',
            field=models.CharField(max_length=22, verbose_name='휴대전화'),
        ),
    ]
