# Generated by Django 2.1.5 on 2019-02-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0021_auto_20190208_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_apl',
            name='tel_no',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='집전화'),
        ),
        migrations.AlterField(
            model_name='ms_apl',
            name='tel_no_g',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='보호자 연락처'),
        ),
    ]
