# Generated by Django 2.1.5 on 2019-02-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0023_mpgm_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msch',
            name='apl_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applies', to='service20.ms_apl', verbose_name='모집시기(MS0022)'),
        ),
    ]
