# Generated by Django 2.1.5 on 2019-02-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0024_auto_20190210_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_cdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_grp_code', models.CharField(max_length=6, verbose_name='그룹코드')),
                ('std_detl_code', models.CharField(max_length=10, verbose_name='공통코드')),
                ('lang_key', models.CharField(max_length=2, verbose_name='언어')),
                ('std_detl_code_nm', models.CharField(max_length=60, verbose_name='공통코드명')),
                ('rmrk', models.CharField(blank=True, max_length=255, null=True, verbose_name='비고')),
                ('rmrk_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='비고2')),
                ('up_std_detl_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='상위공통코드')),
                ('use_indc', models.CharField(default='N', max_length=1, verbose_name='사용여부')),
                ('cls_date', models.CharField(default='00000000', max_length=8, verbose_name='종료일')),
                ('sort_seq_no', models.CharField(default='0000000000', max_length=10, verbose_name='순서')),
                ('co_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='예비 코드')),
                ('plnt', models.CharField(blank=True, max_length=4, null=True, verbose_name='공장')),
                ('sys_id', models.CharField(blank=True, max_length=12, null=True, verbose_name='시스템ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True, verbose_name='예비 텍스트1')),
                ('text2', models.CharField(blank=True, max_length=255, null=True, verbose_name='예비 텍스트2')),
                ('text3', models.CharField(blank=True, max_length=255, null=True, verbose_name='예비 텍스트3')),
                ('text4', models.CharField(blank=True, max_length=255, null=True, verbose_name='예비 텍스트4')),
                ('text5', models.CharField(blank=True, max_length=255, null=True, verbose_name='예비 텍스트5')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
            options={
                'verbose_name': 'Common Code Master Detail',
                'verbose_name_plural': 'Common Code Master Detail',
            },
        ),
        migrations.AlterField(
            model_name='msch',
            name='apl_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applies', to='service20.com_cdd', verbose_name='모집시기(MS0022)'),
        ),
        migrations.AlterUniqueTogether(
            name='com_cdd',
            unique_together={('std_grp_code', 'std_detl_code', 'lang_key')},
        ),
        migrations.AlterIndexTogether(
            name='com_cdd',
            index_together={('std_detl_code_nm', 'std_detl_code')},
        ),
    ]
