# Generated by Django 2.1.5 on 2019-02-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0027_auto_20190210_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_sub',
            name='att_cdd',
            field=models.ForeignKey(blank=True, limit_choices_to={'str_grp_code': 'MS0010'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='service20.com_cdd', verbose_name='속성 CODE'),
        ),
        migrations.AlterField(
            model_name='ms_sub',
            name='att_id',
            field=models.ForeignKey(blank=True, choices=[('MS0010', '지원학년'), ('MS0011', '지원학기'), ('MS0012', '지원성별')], null=True, on_delete=django.db.models.deletion.CASCADE, to='service20.com_cdh', verbose_name='속성ID'),
        ),
        migrations.RemoveField(
            model_name='ms_sub',
            name='att_seq',
        ),
        migrations.AlterUniqueTogether(
            name='ms_sub',
            unique_together={('ms_id', 'att_id')},
        ),
    ]
