# Generated by Django 2.1.5 on 2019-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0028_auto_20190210_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_sub',
            name='att_cdd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='속성 CODE'),
        ),
    ]
