# Generated by Django 2.1.5 on 2019-02-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0029_auto_20190210_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_sub',
            name='att_cdd',
            field=models.ForeignKey(blank=True, limit_choices_to={'str_grp_code': 'MS0010'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='service20.com_cdd', verbose_name='속성 CODE'),
        ),
    ]
