# Generated by Django 2.1.5 on 2019-02-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0031_auto_20190210_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ms_sub',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ms_sub',
            name='att_id',
        ),
        migrations.RemoveField(
            model_name='ms_sub',
            name='ms_id',
        ),
        migrations.DeleteModel(
            name='ms_sub',
        ),
    ]
