# Generated by Django 2.1.5 on 2019-02-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0033_auto_20190210_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp_sub',
            name='att_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='속성 단위'),
        ),
        migrations.AlterField(
            model_name='ms_sub',
            name='att_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service20.com_cdh', verbose_name='속성ID'),
        ),
    ]
