# Generated by Django 2.1.5 on 2019-02-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0034_auto_20190212_1004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ms_sub',
            unique_together={('ms_id', 'att_id', 'att_cdd')},
        ),
    ]
