# Generated by Django 2.1.5 on 2019-02-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0036_auto_20190212_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_cdd',
            name='std_grp_code',
            field=models.CharField(max_length=6, verbose_name='그룹코드'),
        ),
    ]
